#PYGAME VALUES
FPS = 60
SCREEN_WIDTH = 1000
SCREEN_HEIGHT = 1000

#VALUES
WHITE = -1
BLACK = 1
BOARD_WIDTH = 8
BOARD_HEIGHT = 8

SQUARE_SIZE = min(SCREEN_WIDTH, SCREEN_HEIGHT)/max(BOARD_WIDTH, BOARD_HEIGHT)
PIECE_SIZE = SQUARE_SIZE
MOVE_PREVIEW_MARKER_SIZE = int(SQUARE_SIZE/5)
CAPTURE_PREVIEW_MARKER_SIZE = int(SQUARE_SIZE/2)
CAPTURE_PREVIEW_MARKER_WIDTH = SQUARE_SIZE/6

#COLOURS
TRANSPARENT = (0,0,0,0)
WHITE_SQUARE_COLOUR = (234,235,200)
BLACK_SQUARE_COLOUR = (68,134,134)
HIGHLIGHT_COLOUR = (255,255,0,150)
HOVER_COLOUR = (0,0,0,50)
MOVE_PREVIEW_MARKER_COLOUR = (0,0,0,100)
CAPTURE_PREVIEW_MARKER_COLOUR = MOVE_PREVIEW_MARKER_COLOUR
LAST_MOVE_FROM_COLOUR = (255,100,100,150)
LAST_MOVE_TO_COLOUR = LAST_MOVE_FROM_COLOUR


